### PR TITLE
add handling of nil value to authenticate method

### PR DESCRIPTION
**Pull request by Lawrence-Sproul**
I get errors when a null value is submitted to the 'authenticate_{sym}' methods.
Adding this single line to the code prevents the errors and forces an authenticate failure when a nil value, such as a blank password or token, is submitted.

### CODE REVIEW

**Comment by jocubeit** [comment]
Thanks for your PR Lawrence, I'm just going to check whether we need a test for this case before I merge.

**Comment by jocubeit** [comment]
Lawrence I'm having a problem replicating your issue. The default behavior seems to accept `nil` or an empty string and return `false`. Here's the steps I used to test your issue:

``` bash
# Create a new Rails project
rails new attr_digest_test

# Change directory to the new project
cd attr_digest_test

# Create a User model with a digest column
rails g model User name secret_digest
```

``` ruby
# Modify the User model by adding the attr_digest class method
class User < ApplicationRecord
  attr_digest :secret
end
```

``` ruby
# Create the database
rails db:create

# Execute database migrations
rails db:migrate

# Start the Rails console
rails c
```

``` ruby
# Create an User record with a secret
jd = User.create!(name: "John Doe", secret: "abc", secret_confirmation: "abc")
=> #<User id: 1, name: "John Doe", secret_digest: "$argon2i$v=19$m=65536,t=2,p=1$5XLyCxE8cLmW8IeMwzxp...", created_at: "2016-09-30 00:08:08", updated_at: "2016-09-30 00:08:08">

# Test passing no arguments (expect ArgumentError)
jd.authenticate_secret
=> ArgumentError: wrong number of arguments (given 0, expected 1)

# Test passing nil (not sure what to expect)
jd.authenticate_secret(nil)
=> false

# Test passing empty string (expect false)
jd.authenticate_secret("")
=> false

# Test passing an incorrect string (expect false)
jd.authenticate_secret("def")
=> false

# Test passing the correct secret (expect true)
jd.authenticate_secret("abc")
=> true
```

I tested on ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15], Rails 5.0.0.1, attr_digest 1.2.0, on macOS Sierra 10.12.

Can you provide more details? Ruby version? Rails version? attr_digest options?

**Comment by Lawrence-Sproul** [comment]
I too used Ruby 2.3.1p112 and Rails 5.0.0.1 but on the Cloud9 platform.
I have also tried other versions of ruby and rails on this platform.
I use the built-in test suite for rails.
THe code producing the error is:

test "authenticated? should return false for a user with nil digest" do
    assert_not @user.authenticate_remember('')
end

Note: the passed value is '' and the value of @user.remember_digest is nil.

When I view your code there are a few handlers for nil or blank values
(e.g. line 42), but this one segment does not seem to have one.
At first I thought that it may be a difference between OS versions, but on
further review, I think it has to do with the value of
@user.remember_digest being nil.
Although my current code works for me, I am going to try my alternate
version, below, now to see if that also works. I hope the syntax is correct
for my alternate code. I just guessed at what it should be.

Your code:
    def define_authenticate_method(attribute_sym, options)
      define_method "authenticate_#{attribute_sym}" do |value|
        Argon2::Password.verify_password((options[:case_sensitive] ? value
: value.downcase), send("#{attribute_sym}_digest"))
      end
    end

My Current version:
    def define_authenticate_method(attribute_sym, options)
      define_method "authenticate_#{attribute_sym}" do |value|
        unless value.blank?
           Argon2::Password.verify_password((options[:case_sensitive] ?
value : value.downcase), send("#{attribute_sym}_digest"))
        end
      end
    end

My alternate version:
    def define_authenticate_method(attribute_sym, options)
      define_method "authenticate_#{attribute_sym}" do |value|
        unless send("#{attribute_sym}_digest.blank?")
           Argon2::Password.verify_password((options[:case_sensitive] ?
value : value.downcase), send("#{attribute_sym}_digest"))
        end
      end
    end

Respectfully,

Lawrence

**Comment by jocubeit** [comment]
Lawrence, I tried the following in the Rails console:

``` bash
rails c
=> Loading development environment (Rails 5.0.0.1)
```

``` ruby
password = Argon2::Password.new(t_cost: 2, m_cost: 16)
=> #<Argon2::Password:0x007fc8e1a27b58 @t_cost=2, @m_cost=16, @salt="\xF0\xF3\x1C\xEAZ\xE4%\xD7\x82~\xB7\x02\xFE\xC0\xCE\e", @secret=nil>

encrypted = password.create("abc")
=> "$argon2i$v=19$m=65536,t=2,p=1$8PMc6lrkJdeCfrcC/sDOGw$oqrG+NThR96EQa3V4e0+ARmo5ERnKl/goYF1h4wXAJA"

Argon2::Password.verify_password("abc", encrypted)
=> true

Argon2::Password.verify_password("", encrypted)
=> false

Argon2::Password.verify_password(nil, encrypted)
=> false
```

This indicates that passing `blank` or `nil` values to the first argument of the `Argon2::Password#verify_password` method doesn't throw an error.

However, I can see a couple of instances in line 59 that will throw error.

The first is if the value passed is `nil` and the option for `case_sensitive` is `false`. This is the same as calling `nil.downcase` which will throw `NoMethodError: undefined method`downcase' for nil:NilClass`. There should be a guard for this condition.

Since `Argon2::Password#verify_password` is expecting a pair of strings as arguments, what do you think of coercing the value to a string? This would ensure calling `#downcase` wouldn't throw an error. This will allow an encrypted blank digest. The following code shows this is permitted by Argon2::Password: 

``` ruby
password = Argon2::Password.new(t_cost: 2, m_cost: 16)
=> #<Argon2::Password:0x007fc8e1a27b58 @t_cost=2, @m_cost=16, @salt="\xF0\xF3\x1C\xEAZ\xE4%\xD7\x82~\xB7\x02\xFE\xC0\xCE\e", @secret=nil>

encrypted = password.create("")
=> "$argon2i$v=19$m=65536,t=2,p=1$8PMc6lrkJdeCfrcC/sDOGw$eZ5+P7GVipVrNGBt3R8opYfKSnBU3prDUyCEB+CMeAI"

Argon2::Password.verify_password("", encrypted)
=> true
```

You cannot pass `nil` to the `Argon2::Password#new` method, it results in an `Argon2::ArgonHashFail` exception.

To achieve the aforementioned I suggest the following change to line 59:

``` ruby
Argon2::Password.verify_password((options[:case_sensitive] ? "#{value}" : "#{value}".downcase), send("#{attribute_sym}_digest"))
```

The second error condition I can foresee is passing `nil` or `blank` to the second argument of `Argon2::Password#verify_password`. This condition will occur when the stored digest attribute is `nil` or `blank`. Essentially the digested value hasn't been created. This condition should be guarded against as it will throw an `Argon2::ArgonHashFail: Invalid hash` exception.

I don't think this should result in a `false` return value, because the digested value is never getting compared with the passed value. If we returned `false`, it's safe to assume the passed value has been compared against the digested value; and they didn't match. However, in reality, that didn't happen because the digest doesn't exist. It should raise an error, as it does, but it could be a more helpful error; perhaps an `AttrDigest` error explaining a digest doesn't exist.

What are your thoughts about this?

**Comment by Lawrence-Sproul** [comment]
Excellent thoughts and logic. I agree that a better error message should be the response. And I too was bothered by the return of false, but had not thought of an error message. 

Thanks for tanking time to work through this with me. 
I really like using attr_digest. 

Lawrence

**Comment by jocubeit** [comment]
Fantastic! Thanks for your kind words.

I'll create a branch for the new functionality. I'll add a few tests to the suite to ensure everything is working correctly.

I'm thinking I'll add the `secret` option too, and make the memory and time costs options on the `attr_digest` class method. It should be functionally complete then.

I'm hoping to get that done today, I'll let you know when the branch is ready and then maybe you can try it and make sure it works for you. Once we're both happy I'll merge it into master and push a new version.

**Comment by jocubeit** [comment]
Lawrence I have added a new branch https://github.com/brightcommerce/attr_digest/tree/next.

It addresses the two changes discussed above. If you would like to try it you can add the following to your Rails project's Gemfile:

``` ruby
gem 'attr_digest', github: 'brightcommerce/attr_digest', branch: 'next'
```

I am interested to see if these changes address your concerns. I have also added specs to the test suite for these changes. The specs address the 'blank digest' scenario and the 'blank argument' to authenticate_**\* method' scenario.

I will look at adding the other two features now: adding a secret and permitting time and memory cost parameters as options on the `attr_digest` class method.

**Comment by jocubeit** [comment]
I've added the Time and Memory cost options for individual `attr_digest` attributes. The README includes a section on this and specs testing the new setters have been included in the test suite.

This has been included in the `next` branch.

**Comment by jocubeit** [comment]
I've now added the secret key option. This can be set globally or for individual attributes. There's a section in the README covering it. I've also added a spec to cover the new functionality.

I've managed to maintain 100% code coverage in all the tests.

**Comment by jocubeit** [comment]
I've just updated Argon2 to version 1.1.1 (in `next` branch) which was released about 12 days ago. All tests pass.

**Comment by jocubeit** [comment]
So all changes are done, let me know how you go testing this branch with your code. If all goes well, I'll merge the changes into master, update the CHANGELOG and release a new version to RubyGems.

**Comment by jocubeit** [comment]
@Lawrence-Sproul I'm going to push this through as a new version later today under the assumption it's addressed all your needs. The tests all pass and the gem will be feature complete.

**Comment by Lawrence-Sproul** [comment]
thank you.  i will try it later this week.

Respectfully,

Lawrence

**Comment by Lawrence-Sproul** [comment]
Jurgen,

I really like the error message that you set up. It says exactly what is
happening.

A future feature that would be nice is to set other constraints on the
attribute, such as minimum length.
Presently I set other restrictions using 'validates' in the model, which is
fine.
But then, I also worry about putting too many things in something that
already works very well.
I just have to remember to not set a validate that conflicts or duplicates
what attr_digest is doing.

Thank you again for making such a good gem.

Lawrence

Respectfully,

Lawrence

On Tue, Oct 18, 2016 at 10:47 PM, Lawrence Sproul <lawrence.sproul@gmail.com

**Comment by jocubeit** [comment]
@Lawrence-Sproul I'm not opposed to adding extra validations, it does make sense to have them on the attribute being digested. Do you have a preference (other than minimum and maximum length) of which validations I should include?

**Comment by Lawrence-Sproul** [comment]
Jurgen,

That is a tough question. there are a number of things that might be
useful, but I think many are better handled separately.
Almost anything that could be in a validates statement could be put in, but
it could quickly lead to bloat if not handled properly.

Perhaps my first priority would be a simplified minimum complexity (
has_lower_case = 0; has_upper_case = 0 ; has_digits = 0; has_symbols=0;
symbol_set={ @,#,$,% }  ) where the number indicates the minimum quantity
of each, with a default of 0 or 1. and then the values are combined into a
REGEX validation or group of validations.

Thanks,
Lawrence

Respectfully,

Lawrence

**Comment by jocubeit** [comment]
Thanks for getting back to me @Lawrence-Sproul.

I have decided to add both `format` and `length` validators from Rails as options to **attr_digest**. These are the only ones that make sense to me.

I worked on `format` this morning and have added two tests to maintain code coverage and ensure both negative and positive results are tested. I have added this to the `next` branch. The options hash passed to the `format` are what Rails would expect and are passed as is to the Rails format validator. I have also added a section in the README to explain this.

I would appreciate if you have time to check this addition. I will work on the `length` option now and inform you when it has been added.

**Comment by jocubeit** [comment]
@Lawrence-Sproul I have added the `length` validation option with tests. All tests are passing and code coverage remains at 100%. I've added a section in the README covering the `length` option.

```
gem 'attr_digest', github: 'brightcommerce/attr_digest', branch: 'next'
```

Would you mind testing this new functionality to see if it meets your needs? I believe we're ready to push out the new version.

**Comment by Lawrence-Sproul** [comment]
Thanks for working on this. I hope to test it soon. Meanwhile I put
together a REGEX string that incorporates the complexity items that I
mentioned:

PASSWORD_COMPLEXITY_REGEX =
"^(?=(._[^A-Za-z0-9]){#{has_symbols},})(?=(._[A-Z]){#{has_upper_case},})(?=(._[a-z]){has_lower_case},})(?=(._\d){#{has_digits},}).+"

Respectfully,

Lawrence

**Comment by Lawrence-Sproul** [comment]
I like the way you did it. Lots of flexibility. And it seems to work the
way I would expect.
I do still like the simplicity of using my complexity regex, though the
var_names could be better.
Some devs don't take time to figure out REGEX but just grab something from
google.
I haven't figured out a good value for the symbol_set yet, so I just leave
it at the default for anything that's not a-z, A-Z, or 0-9 for now.
I even tried my regex with a value of 16. It takes a bit to think of
something that fits, but it worked as expected.

Respectfully,

Lawrence

On Thu, Nov 10, 2016 at 11:47 AM, Lawrence Sproul <lawrence.sproul@gmail.com

**Comment by jocubeit** [comment]
@Lawrence-Sproul I think the Regex for symbols is `\W` (which indicates non-alphanumeric characters) Can you give me an example of the minimum password complexity rules you are chasing?

Are your rules simply that the password must have at least one lowercase, one uppercase, one digit and one symbol (non-word character)?

**Comment by Lawrence-Sproul** [comment]
I don't have a specific target, just looking for easy configuration of complexity.

**Comment by jocubeit** [comment]
OK, I think almost any format can be created using a Regex. For instance:

The password must then contain characters from at least 3 of the following 4 rules:
1. Upper case
2. Lower case
3. Numbers
4. Non-alphanumeric

```
(^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*$)?(^(?=.*\d)(?=.*[a-z])(?=.*[@#$%^&+=]).*$)?(^(?=.*\d)(?=.*[A-Z])(?=.*[@#$%^&+=]).*$)?(^(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$)?
```

Given this sort of complexity can be passed in via Regex I think we have everything covered off. If it's too complex to put into a regular expression then I think it should be handled separately in the model with a custom validation.

I'm keen to merge the `next` branch and push the new version. What are your thoughts?

**Comment by jocubeit** [comment]
All concerns and new functionality addressed in #3. Closing in favor of merging that PR. Thanks for your support @Lawrence-Sproul. I'll push the new version to RubyGems today.

**Comment by Lawrence-Sproul** [comment]
Thanks for working with me on this. I agree that the way you did it provides everything I need.

**Pull request closed without merging**
